Revert "piccolo: Switch to Clang build by default"
This reverts commit 39cd1f76ac503111aafb7453bbc5652b59061bcd.

* display-caf/msm8916 doesn't build with clang:
  error: implicit conversation changes signedness [-Wsign-conversion]